# Generated by Django 6.0.4 on 2026-07-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
    ]
