# Generated by Django 6.0.4 on 2026-08-06 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_turno_pagado'),
        ('profesionales', '0025_orientacion_alter_psicologo_orientacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_portal', to='profesionales.psicologo')),
            ],
            options={
                'verbose_name': 'Ingreso al portal',
                'verbose_name_plural': 'Ingresos al portal',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'psicologo')},
            },
        ),
    ]
