# Generated by Django 5.0.4 on 2026-08-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_ingresoportal'),
        ('profesionales', '0026_psicologo_direccion_consultorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='origen',
            field=models.CharField(choices=[('manual', 'Cargado por el profesional'), ('publico', 'Reservado por el paciente')], default='manual', help_text='"Reservado por el paciente" es lo que dispara el mail de aviso al profesional.', max_length=20),
        ),
        migrations.CreateModel(
            name='DiaNoAtiende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(verbose_name='Desde')),
                ('fecha_hasta', models.DateField(verbose_name='Hasta')),
                ('motivo', models.CharField(blank=True, max_length=100)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_atiende', to='profesionales.psicologo')),
            ],
            options={
                'verbose_name': 'Día que no atiende',
                'verbose_name_plural': 'Días que no atiende',
                'ordering': ['fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')], verbose_name='Día de la semana')),
                ('hora_desde', models.TimeField(verbose_name='Desde')),
                ('hora_hasta', models.TimeField(verbose_name='Hasta')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad_semanal', to='profesionales.psicologo')),
            ],
            options={
                'verbose_name': 'Bloque de disponibilidad semanal',
                'verbose_name_plural': 'Disponibilidad semanal',
                'ordering': ['dia_semana', 'hora_desde'],
            },
        ),
    ]
