# Generated by Django 5.0.4 on 2026-08-20 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_turno_modalidad_turno_origen_dianoatiende_and_more'),
        ('profesionales', '0027_psicologo_fecha_alta_psicologo_monto_pagado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('concepto', models.CharField(blank=True, max_length=200, verbose_name='Concepto')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('concepto', models.CharField(blank=True, help_text='Ej: Alta, mensualidad agosto', max_length=200, verbose_name='Concepto')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('psicologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_recibidos', to='profesionales.psicologo')),
            ],
            options={
                'verbose_name': 'Pago recibido',
                'verbose_name_plural': 'Pagos recibidos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
