# Generated by Django 6.0.4 on 2026-08-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_gasto_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto bruto (antes de la comisión de MP)'),
        ),
        migrations.AddField(
            model_name='pago',
            name='mp_payment_id',
            field=models.CharField(blank=True, help_text='Evita importar el mismo pago dos veces', max_length=40, null=True, unique=True, verbose_name='ID de pago en Mercado Pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='origen',
            field=models.CharField(choices=[('manual', 'Cargado a mano'), ('transferencia', 'Transferencia (Mercado Pago)'), ('suscripcion', 'Suscripción (Mercado Pago)')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='pagador_nombre',
            field=models.CharField(blank=True, help_text='Tal cual lo reporta MP -- útil para asignar el pago a mano si no coincide con nadie cargado', max_length=150, verbose_name='Nombre del pagador en Mercado Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto neto recibido'),
        ),
    ]
