# Generated by Django 6.0.4 on 2026-09-07 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesionales', '0027_psicologo_fecha_alta_psicologo_monto_pagado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Se muestra en la página pública del curso.')),
                ('presentador', models.CharField(max_length=150)),
                ('presentador_detalle', models.CharField(blank=True, help_text='Ej: "Esp. en Psicología Clínica · UBA"', max_length=150)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio_red_consulta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Red Consulta')),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio público general')),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, help_text='Vacío = sin límite. Cuenta solo las inscripciones ya pagadas.', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está apagado, la página pública da 404.')),
            ],
            options={
                'verbose_name': 'Curso / Taller',
                'verbose_name_plural': 'Cursos / Talleres',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=30)),
                ('es_red_consulta', models.BooleanField(default=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mp_preference_id', models.CharField(blank=True, max_length=100)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('aprobado', 'Pagado'), ('rechazado', 'Rechazado / cancelado')], default='pendiente', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='cursos.curso')),
                ('psicologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_cursos', to='profesionales.psicologo')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
