# Generated by Django 6.0.4 on 2026-09-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_taller_historia_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='presentador_bio',
            field=models.TextField(blank=True, help_text='Bio corta con formación/experiencia del presentador -- se muestra en un popup al hacer click en su nombre, para darle credibilidad. Vacío = el nombre no es clickeable.'),
        ),
    ]
