# Generated by Django 6.0.4 on 2026-09-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_taller_hc_presentador_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='presentador_foto',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/presentadores/'),
        ),
    ]
