# Generated by Django 5.0.4 on 2026-09-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_deshabilitar_popup_presentador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='precio_red_consulta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Miembros Atención Psi'),
        ),
    ]
