# Generated by Django 5.0.4 on 2026-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_actualizar_precios_taller_hc'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='presentador_email',
            field=models.EmailField(blank=True, help_text='Si se completa, se le avisa por mail cada vez que alguien se inscribe y paga este curso. Vacío = no se le avisa a nadie.', max_length=254),
        ),
    ]
