# Generated by Django 6.0.4 on 2026-05-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='psicologos/')),
                ('ciudad', models.CharField(blank=True, help_text='Ej: Bahía Blanca. Dejar vacío si es solo Online', max_length=50, null=True)),
                ('modalidad', models.CharField(help_text='Ej: Presencial / Online', max_length=50)),
                ('enfoque', models.CharField(help_text='Ej: Psicoanálisis', max_length=50)),
                ('dirigido_a', models.CharField(help_text='Ej: Adultos, Niños', max_length=50)),
                ('especialidades', models.TextField(help_text='Esto se verá solo en el perfil detallado')),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
