# Generated by Django 6.0.4 on 2026-05-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='enfoque',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='especialidades',
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='dirigido_a',
            field=models.CharField(choices=[('Adultos', 'Adultos'), ('Niños', 'Niños'), ('Adolescentes', 'Adolescentes'), ('Parejas', 'Parejas'), ('Adultos y Adolescentes', 'Adultos y Adolescentes')], default='Adultos', max_length=50),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='modalidad',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('Híbrido', 'Híbrido')], default='Online', max_length=20),
        ),
    ]
