# Generated by Django 6.0.4 on 2026-05-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_remove_psicologo_email_remove_psicologo_enfoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='dirigido_a',
            field=models.CharField(default='Adultos', max_length=255),
        ),
    ]
