# Generated by Django 6.0.4 on 2026-05-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_alter_psicologo_dirigido_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve biografía o resumen profesional'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='obras_sociales',
            field=models.TextField(blank=True, help_text='Lista de obras sociales con las que trabaja'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='orientacion',
            field=models.CharField(blank=True, help_text='Ej: TCC, Psicoanálisis, Sistémica', max_length=100),
        ),
    ]
