# Generated by Django 6.0.4 on 2026-05-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0004_psicologo_descripcion_psicologo_obras_sociales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='modalidad',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('Presencial - Online', 'Presencial - Online')], default='Online', max_length=20),
        ),
    ]
