# Generated by Django 6.0.4 on 2026-05-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0006_alter_psicologo_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='modalidad',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('PresencialOnline', 'PresencialOnline')], default='PresencialOnline', max_length=20),
        ),
    ]
