# Generated by Django 6.0.4 on 2026-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0009_alter_psicologo_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='modalidad',
            field=models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('Presencial - Online', 'Presencial - Online')], default='Presencial - Online', max_length=20),
        ),
    ]
