# Generated by Django 6.0.4 on 2026-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0010_psicologo_slug_alter_psicologo_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
