# Generated by Django 6.0.4 on 2026-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0011_alter_psicologo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
