# Generated by Django 6.0.4 on 2026-05-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0012_psicologo_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='modalidad',
        ),
        migrations.AddField(
            model_name='psicologo',
            name='modalidades',
            field=models.ManyToManyField(blank=True, to='profesionales.modalidad'),
        ),
    ]
