# Generated by Django 6.0.4 on 2026-05-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0013_modalidad_remove_psicologo_modalidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Público',
                'verbose_name_plural': 'Públicos',
            },
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='dirigido_a',
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='obras_sociales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='orientacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, to='profesionales.publico'),
        ),
    ]
