# Generated by Django 6.0.4 on 2026-07-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0020_ciudad_padre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta de login para que este profesional entre a /portal/. Se crea desde Usuarios en el admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psicologo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso al portal'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
