# Generated by Django 6.0.4 on 2026-07-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0021_psicologo_usuario_alter_ciudad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Se marca sola al crear el acceso con contraseña provisoria. Se desmarca cuando el profesional la cambia.', verbose_name='Debe cambiar la contraseña'),
        ),
    ]
