# Generated by Django 6.0.4 on 2026-08-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0022_psicologo_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no aparece en el buscador público del sitio.', verbose_name='Activo'),
        ),
    ]
