# Generated by Django 5.0.4 on 2026-08-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0023_psicologo_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publico',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Público', 'verbose_name_plural': 'Públicos'},
        ),
        migrations.AddField(
            model_name='publico',
            name='orden',
            field=models.PositiveIntegerField(default=100, help_text='Los números más bajos aparecen primero. Empatados se ordenan alfabéticamente.', verbose_name='Orden'),
        ),
    ]
