# Generated by Django 6.0.4 on 2026-08-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0024_alter_publico_options_publico_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('orden', models.PositiveIntegerField(default=100, help_text='Los números más bajos aparecen primero. Empatados se ordenan alfabéticamente.', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Orientación',
                'verbose_name_plural': 'Orientaciones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='orientacion',
            field=models.CharField(blank=True, help_text='Texto libre para el perfil (lo que escribe cada profesional). Para que se pueda filtrar en el buscador, marcá también las Orientaciones de abajo.', max_length=100),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='orientaciones',
            field=models.ManyToManyField(blank=True, help_text='Categorías fijas para el filtro del buscador (Psicoanálisis, Cognitivo Conductual, etc.). Podés marcar más de una.', to='profesionales.orientacion', verbose_name='Orientaciones (filtro)'),
        ),
    ]
