# Generated by Django 5.0.4 on 2026-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0025_orientacion_alter_psicologo_orientacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='direccion_consultorio',
            field=models.CharField(blank=True, help_text='Se muestra en la reserva y en el mail de aviso cuando el turno es presencial.', max_length=255, verbose_name='Dirección del consultorio'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='duracion_turno_min',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 minutos'), (45, '45 minutos'), (60, '60 minutos')], default=45, help_text='Se usa para partir la disponibilidad semanal en horarios reservables desde el turnero público.', verbose_name='Duración de los turnos'),
        ),
    ]
