# Generated by Django 5.0.4 on 2026-08-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0026_psicologo_direccion_consultorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='plan',
            field=models.CharField(blank=True, choices=[('avanzado', 'Avanzado'), ('premium', 'Premium'), ('master', 'Master')], max_length=20, verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('suscripcion', 'Suscripción')], max_length=20, verbose_name='Transferencia o suscripción'),
        ),
    ]
